# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpursAPI(object):
    def setupUi(self, SpursAPI):
        SpursAPI.setObjectName("SpursAPI")
        SpursAPI.resize(892, 573)
        self.centralwidget = QtWidgets.QWidget(SpursAPI)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcome_page = QtWidgets.QWidget()
        self.welcome_page.setObjectName("welcome_page")
        self.stackedWidget.addWidget(self.welcome_page)
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.login_page)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_fields = QtWidgets.QWidget(self.login_page)
        self.widget_fields.setMaximumSize(QtCore.QSize(280, 290))
        self.widget_fields.setObjectName("widget_fields")
        self.email_input = QtWidgets.QLineEdit(self.widget_fields)
        self.email_input.setGeometry(QtCore.QRect(30, 40, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.email_input.setFont(font)
        self.email_input.setObjectName("email_input")
        self.password_input = QtWidgets.QLineEdit(self.widget_fields)
        self.password_input.setGeometry(QtCore.QRect(30, 86, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.password_input.setFont(font)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.login_btnv = QtWidgets.QPushButton(self.widget_fields)
        self.login_btnv.setGeometry(QtCore.QRect(30, 140, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login_btnv.setFont(font)
        self.login_btnv.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_btnv.setObjectName("login_btnv")
        self.create_account_go = QtWidgets.QPushButton(self.widget_fields)
        self.create_account_go.setGeometry(QtCore.QRect(30, 200, 221, 23))
        self.create_account_go.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create_account_go.setObjectName("create_account_go")
        self.horizontalLayout.addWidget(self.widget_fields)
        self.stackedWidget.addWidget(self.login_page)
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.stackedWidget.addWidget(self.main_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        SpursAPI.setCentralWidget(self.centralwidget)

        self.retranslateUi(SpursAPI)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SpursAPI)

    def retranslateUi(self, SpursAPI):
        _translate = QtCore.QCoreApplication.translate
        SpursAPI.setWindowTitle(_translate("SpursAPI", "SpursAPI"))
        self.email_input.setPlaceholderText(_translate("SpursAPI", "Email"))
        self.password_input.setPlaceholderText(_translate("SpursAPI", "Password"))
        self.login_btnv.setText(_translate("SpursAPI", "Login"))
        self.create_account_go.setText(_translate("SpursAPI", "I don\'t have an account ? create account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpursAPI = QtWidgets.QMainWindow()
    ui = Ui_SpursAPI()
    ui.setupUi(SpursAPI)
    SpursAPI.show()
    sys.exit(app.exec_())
