# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpursAPI(object):
    def setupUi(self, SpursAPI):
        SpursAPI.setObjectName("SpursAPI")
        SpursAPI.resize(888, 573)
        self.centralwidget = QtWidgets.QWidget(SpursAPI)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcome_page = QtWidgets.QWidget()
        self.welcome_page.setObjectName("welcome_page")
        self.stackedWidget.addWidget(self.welcome_page)
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.stackedWidget.addWidget(self.login_page)
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.stackedWidget.addWidget(self.main_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        SpursAPI.setCentralWidget(self.centralwidget)

        self.retranslateUi(SpursAPI)
        QtCore.QMetaObject.connectSlotsByName(SpursAPI)

    def retranslateUi(self, SpursAPI):
        _translate = QtCore.QCoreApplication.translate
        SpursAPI.setWindowTitle(_translate("SpursAPI", "SpursAPI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpursAPI = QtWidgets.QMainWindow()
    ui = Ui_SpursAPI()
    ui.setupUi(SpursAPI)
    SpursAPI.show()
    sys.exit(app.exec_())
